name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: macOS-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Install RubyGems
      run: |
        gem install --user bundler
        bundle install --retry=3 --jobs=4

    - name: Run RuboCop
      run: |
        bundle exec rubocop

    - name: Cleanup macOS
      run: |
        sudo rm -rf /Applications/Xcode.app \
                    /Library/Developer/CommandLineTools
        sudo pkgutil --forget com.apple.pkg.CLTools_Executables
        sudo xcode-select --reset

    - name: CI Tests
      run: |
        export PATH=/usr/bin:/bin:/usr/local/bin
        ruby uninstall -d >/dev/null
        ruby uninstall -f >/dev/null
        ruby install --force-curl
        ruby uninstall -f >/dev/null
        ruby install
        brew install ack
        ruby uninstall -f >/dev/null
